services:
  alice:
    platform: linux/x86_64
    image: ghcr.io/zenchain-protocol/zenchain-testnet:latest
    ports:
      - "9944:9944"
      - "9615:9615"
    command:
      - "./usr/bin/zenchain-node"
      - "--node-key=0000000000000000000000000000000000000000000000000000000000000001"
      - "--base-path=/tmp/alice"
      - "--chain=local"
      - "--port=30333"
      - "--validator"
      - "--alice"
      - "--bootnodes=/dns/bob/tcp/30333/p2p/12D3KooWHdiAxVd8uMQR1hGWXccidmfCwLqcMpGwR6QcTP6QRMuD"
      - "--unsafe-rpc-external"
      - "--rpc-cors=all"

  bob:
    platform: linux/x86_64
    image: ghcr.io/zenchain-protocol/zenchain-testnet:latest
    ports:
      - "9945:9944"
    command:
      - "./usr/bin/zenchain-node"
      - "--node-key=0000000000000000000000000000000000000000000000000000000000000002"
      - "--base-path=/tmp/bob"
      - "--chain=local"
      - "--port=30333"
      - "--validator"
      - "--bob"
      - "--bootnodes=/dns/alice/tcp/30333/p2p/12D3KooWEyoppNCUx8Yx66oV9fJnriXwCcXwDDUA2kj6vnc6iDEp"
      - "--rpc-cors=all"
      - "--unsafe-rpc-external"
  
  redis:
    platform: linux/x86_64
    image: redis:latest
    command: redis-server --requirepass your_redis_password
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  api:
    platform: linux/x86_64
    build: https://github.com/zenchain-protocol/forta-storage.git
    ports:
      - "8080:8080"
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: your_redis_password
      NODE_ENV: development # or production, depending on what you want to test
      NODE_PORT: 8080
      VALUE_BLOCKSCOUT_TOKEN: your-blockscout-api-key
      VALUE_ETHERSCAN_TOKEN: your-etherscan-token
      VALUE_ZENCHAIN_API_KEY: example_zenchain_api_key
      VALUE_ZETTABLOCK_API_KEY: example_zettablock_api_key
    depends_on:
      - redis

  app:
    platform: linux/x86_64
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      ARBITRARY_BLOCKSCOUT_ENDPOINT: https://zentrace.io #https://arbitrary.blockscount.com
      EVM_RPC: http://alice:9944 #https://cloudflare-eth.com
      NODE_ENV: development
      FORTA_BOT_ID: 1 #0x4c7e56a9a753e29ca92bd57dd593bdab0c03e762bdd04e2bc578cb82b842c1f3
      FORTA_CHAIN_ID: 8408 #1
      STORAGE_API_URL: http://api:8080
    ports:
      - "3000:3000"
    depends_on:
      - alice
      - bob
      - api

volumes:
  redis_data: