services:
  alice:
    image: krisbit/zenchain-testnet #your-image-rpo/your-evm-node-image
    ports:
      - "9944:9944"
      - "9615:9615"
    command:
      - "./usr/bin/zenchain-node" #./user/bin/your-evm-node-binary
      - "--node-key=0000000000000000000000000000000000000000000000000000000000000001"
      - "--base-path=/tmp/alice"
      - "--chain=local"
      - "--port=30333"
      - "--validator"
      - "--alice"
      - "--bootnodes=/dns/bob/tcp/30333/p2p/12D3KooWHdiAxVd8uMQR1hGWXccidmfCwLqcMpGwR6QcTP6QRMuD"
      - "--unsafe-rpc-external"
      - "--log=sub-libp2p=trace"
      - "--rpc-cors=all"

  bob:
    image: krisbit/zenchain-testnet #your-image-rpo/your-evm-node-image
    ports:
      - "9945:9944"
    command:
      - "./usr/bin/zenchain-node" #./user/bin/your-evm-node-binary
      - "--node-key=0000000000000000000000000000000000000000000000000000000000000002"
      - "--base-path=/tmp/bob"
      - "--chain=local"
      - "--port=30333"
      - "--validator"
      - "--bob"
      - "--bootnodes=/dns/alice/tcp/30333/p2p/12D3KooWEyoppNCUx8Yx66oV9fJnriXwCcXwDDUA2kj6vnc6iDEp"
      - "--rpc-cors=all"
      - "--unsafe-rpc-external"
      - "--log=sub-libp2p=trace"

  dave:
    image: krisbit/zenchain-testnet #your-image-rpo/your-evm-node-image
    ports:
      - "9946:9944"
    command:
      - "./usr/bin/zenchain-node" #./user/bin/your-evm-node-binary
      - "--node-key=0000000000000000000000000000000000000000000000000000000000000003"
      - "--base-path=/tmp/light"
      - "--chain=local"
      - "--port=30333"
      - "--bootnodes=/dns/alice/tcp/30333/p2p/12D3KooWEyoppNCUx8Yx66oV9fJnriXwCcXwDDUA2kj6vnc6iDEp"
      - "--bootnodes=/dns/bob/tcp/30333/p2p/12D3KooWHdiAxVd8uMQR1hGWXccidmfCwLqcMpGwR6QcTP6QRMuD"
      - "--rpc-cors=all"
      - "--unsafe-rpc-external"
      - "--log=sub-libp2p=trace"

  redis:
    image: redis:latest
    command: redis-server --requirepass your_redis_password
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  api:
    build: https://github.com/zenchain-protocol/forta-storage.git
    ports:
      - "8080:8080"
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: your_redis_password
      NODE_ENV: development # or production, depending on what you want to test
      NODE_PORT: 8080
      VALUE_ZETTABLOCK_API_KEY: example_zettablock_api_key
    depends_on:
      - redis

  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      EVM_RPC: http://alice:9944 #https://cloudflare-eth.com/
      FORTA_BOT_ID: 1
      FORTA_CHAIN_ID: 8408 #1
      NODE_ENV: development
      STORAGE_API_URL: http://api:8080
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - alice
      - bob
      - dave
      - api

volumes:
  redis_data: